apiVersion: v1
kind: Service
metadata:
  name: chat-docs-ui
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    app: chat-docs-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: chat-docs-ui

# Made with Bob
