{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "poc-onprem.serviceAccountName" . }}
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    {{- include "poc-onprem.labels" . | nindent 4 }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

# Made with Bob
