apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: {{ include "poc-onprem.namespace" . }}
  labels: {{- include "poc-onprem.labels" . | nindent 4 }}
type: Opaque
stringData:
  fernet-key: {{ .Values.airflow.secrets.fernetKey | quote }}
  internal-api-secret-key:
    {{ .Values.airflow.secrets.internalApiSecretKey | quote }}
  jwt-secret: {{ .Values.airflow.secrets.jwtSecret | quote }}

# Made with Bob
