apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: {{ include "poc-onprem.namespace" . }}
  labels: {{- include "poc-onprem.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.credentials.rootUser | quote }}
  root-password: {{ .Values.minio.credentials.rootPassword | quote }}

# Made with Bob
