apiVersion: v1
kind: Secret
metadata:
  name: postgres-pdf-secrets
  namespace: {{ include "poc-onprem.namespace" . }}
  labels: {{- include "poc-onprem.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresql.pdf.credentials.username | quote }}
  postgres-password: {{ .Values.postgresql.pdf.credentials.password | quote }}
  postgres-db: {{ .Values.postgresql.pdf.credentials.database | quote }}

# Made with Bob
