apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-llm-chat-pvc
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    app: ollama-llm-chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

# Made with Bob
