apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-airflow-db-pvc
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    app: pg-airflow-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

# Made with Bob
