apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-typing-pdf-extractor-db-pvc
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    app: pg-typing-pdf-extractor-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

# Made with Bob
