apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-vector-db-pvc
  namespace: {{ include "poc-onprem.namespace" . }}
  labels:
    app: qdrant-vector-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

# Made with Bob
